-- AlterTable
ALTER TABLE `aievent` MODIFY `eventType` ENUM('FACE_RECOGNIZED', 'FACE_NOT_RECOGNIZED', 'FIREARM', 'SHARP_OBJECT', 'PHONE', 'DRUGS', 'FIGHT', 'LOITERING', 'BULLYING', 'SNEAKING', 'TRUANCY', 'STEALING', 'EXAM_CHEATING', 'VANDALISM', 'SMOKING', 'CROWDING', 'UNIDENTIFIED_PERSON', 'CAMERA_OFFLINE', 'CAMERA_ONLINE', 'SMOKE', 'FIRE', 'INTRUSION') NOT NULL;
